name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Value
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID}}
